dashbord/urls.py
from django.urls import path
from . import views

app_name="dashbord"
urlpatterns = [
    path('index/', views.index_views, name='index'),
    path('', views.dashboad_views, name='dashboad') ,
]

eleve/urls.py
from django.urls import path
from . import views

app_name="eleve"
urlpatterns = [
    path('', views.eleve_views, name='eleve1'),
    path('ajout_eleve/', views.ajout_eleve_views, name='ajout_eleve'),
    path('modifier_eleve/', views.modifier_eleve_views, name='modifier_eleve'),
]

rapport/urls.py
from django.urls import path
from . import views

app_name="rapport"
urlpatterns = [
    path('', views.rapport_views, name='rapport1'),
] 

teacher/urls.py
from django.urls import path
from . import views

app_name="teacher"
urlpatterns = [
    path('', views.professeurs_views, name='professeurs'),
    path('modifier_prof/', views.modifier_prof_views, name='modifier_prof'),
    path('ajout_prof/', views.ajout_prof_views, name='ajout_prof'),
]

user/urls.py
from django.urls import path
from . import views


app_name="user"
urlpatterns = [
     path('', views.utilisateurs_views, name='utilisateurs'),
    path('ajout_utilisateur/', views.ajout_utilisateur_views, name='ajout_utilisateur'),
    path('modifier_utilisateur/', views.modifier_utilisateur_views, name='modifier_utilisateur'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eleve/', include("eleve.urls")),
    path('dashbord/', include("dashbord.urls")),
    path('rapport/', include("rapport.urls")),
    path('teacher/', include("teacher.urls")),
    path('user/', include("user.urls")),
    
]

eleve/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    birth_date = models.DateField()
    phone = models.CharField(max_length=14)
    city = models.CharField(max_length=20)
    level = models.CharField(max_length=20)

rapport/models.py
from django.db import models

# Create your models here.

teacher/models.py
from django.db import models

# Create your models here.

class Teacher(models.Model):
    id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.CharField(max_length=3)
    phone = models.CharField(max_length=14)
    city = models.CharField(max_length=20)
    subject = models.CharField(max_length=20)

user/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    id = models.AutoField(primary_key=True)
    Pseudo = models.CharField(max_length=10)
    Password = models.CharField(max_length=30)
    Confirm_password = models.CharField(max_length=30)

eleve/forms.py
from django import forms

class StudentForm(forms.Form):
    Nom = forms.CharField(max_length=10)
    Prenom = forms.CharField(max_length=30)
    Matricule = forms.CharField(max_length=30)
    Naissance = forms.DateField()
    Telephone = forms.CharField(max_length=14)
    Ville = forms.CharField(max_length=20)
    Niveau = forms.CharField(max_length=20)

teacher/forms.py
from django import forms

class TeacherForm(forms.Form):
    Nom = forms.CharField(max_length=10)
    Prenom = forms.CharField(max_length=30)
    Genre = forms.CharField(max_length=30)
    Matière = forms.CharField(max_length=30)
    Matricule = forms.CharField(max_length=30)
    Age = forms.CharField(max_length=30)
    Telephone = forms.CharField(max_length=14)
    Ville = forms.CharField(max_length=20)
    

user/forms.py
from django import forms

class UserForm(forms.Form):
    Admin = forms.CharField(max_length=10)
    Ancien_mot_de_passe = forms.CharField(max_length=30)
    Nouveau_mot_de_passe = forms.CharField(max_length=30)
    Confirmer_le_nouveau_mot_de_passe = forms.CharField(max_length=30)
    
class UserAdd(forms.Form):
    Pseudo = forms.CharField(max_length=30)
    mot_de_passe = forms.CharField(max_length=30)
    Confirmer_mot_de_passe = forms.CharField(max_length=30)

dashbord/views.py
from django.shortcuts import render


# Create your views here.
def index_views(request):
    return render(request, 'dashbord/index.html/')

def dashboad_views(request):
    return render(request, 'dashbord/dashboad.html/')

eleve/views.py
from django.shortcuts import render
from .forms import StudentForm


# Create your views here.

def eleve_views(request):
    context = {
        'nom':"IRIE",
        'prenom':"Innocent",
    }
    return render(request, 'eleve/eleve1.html/', context)

def ajout_eleve_views(request):
    form = StudentForm()
    context = {'form':form}
    return render(request, 'eleve/ajout_eleve.html/', context)

def modifier_eleve_views(request):
    form = StudentForm()
    context = {'form':form}
    return render(request, 'eleve/modifier_eleve.html/', context)

rapport/views.py
from django.shortcuts import render

# Create your views here.

def rapport_views(request):
    return render(request, 'rapport/rapport1.html/')

teacher/views.py
from django.shortcuts import render
from .forms import TeacherForm

# Create your views here.

def professeurs_views(request):
    return render(request, 'teacher/professeurs.html/')

def ajout_prof_views(request):
    form = TeacherForm()
    context = {'form':form}
    return render(request, 'teacher/ajout_prof.html/', context)


def modifier_prof_views(request):
    form = TeacherForm()
    context = {'form':form}
    return render(request, 'teacher/modifier_prof.html/', context)

user/views.py
from django.shortcuts import render
from .forms import UserForm
from .forms import UserAdd

# Create your views here.

def utilisateurs_views(request):
    return render(request, 'user/utilisateurs.html/')


def ajout_utilisateur_views(request):
    form = UserAdd()
    context = {'form':form}
    return render(request, 'user/ajout_utilisateur.html/', context)


def modifier_utilisateur_views(request):
    form = UserForm()
    context = {'form':form}
    return render(request, 'user/modifier_utilisateur.html/', context)

dashbord/templates/dashbord/dashboad.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tableau de bord</title>
    <link rel="stylesheet" href="{% static 'dashbord/CSS/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar">
        <h2>Mon Etab</h2>
        <hr>
        <ul>
            <li class="active">
                <a href="{% url 'dashbord:dashboad'%}"><i class="fas fa-tachometer-alt"></i> Tableau de bord</a>
            </li>
            <li >
                <a href="{% url 'eleve:eleve1'%}"><i class="fas fa-user-graduate"></i> Élèves</a>
            </li>
            <li>
                <a href="{% url 'teacher:professeurs'%}"><i class="fas fa-chalkboard-teacher"></i> Professeurs</a>
            </li>
            <li>
                <a href="{% url 'user:utilisateurs'%}"><i class="fas fa-chart-line"></i> utilisateurs</a>
            </li>
            <li>
                <a href="{% url 'rapport:rapport1'%}"><i class="fas fa-chart-line"></i> Rapport</a>
            </li>
        </ul>
        <hr style="margin-top:270px;">
        <ul>
            <li>
                <a href="{% url 'dashbord:index'%}"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            </li>
        </ul>
    </div>
    <div class="content">
        <div class="back-button" style="justify-content: flex-start;" >
            <h1 style="color:black;">Tableau de bord</h1>
        </div>
        <div class="card-container">
            <div class="card">Nombre d'élèves<br>128 100</div>
            <div class="card">Nombre de professeurs<br>128 100</div>
            <div class="card">Nombre d'utilisateurs<br>128 100</div>
            <div class="card">
                <canvas id="pie-chart"></canvas>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static 'dashbord/JS/scripte.js'%}"></script>
</body>
</html>

eleve/templates/eleve/ajout_eleve.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un élève</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'eleve/CSS/styles.css' %}">
</head>
<body>
    <div class="sidebar">
        <h2>Mon Etab</h2>
        <hr>
        <ul>
            <li >
                <a href="{% url 'dashbord:dashboad'%}"><i class="fas fa-tachometer-alt"></i> Tableau de bord</a>
            </li>
            <li class="active">
                <a href="{% url 'eleve:eleve1'%}"><i class="fas fa-user-graduate"></i> Élèves</a>
            </li>
            <li>
                <a href="{% url 'teacher:professeurs'%}"><i class="fas fa-chalkboard-teacher"></i> Professeurs</a>
            </li>
            <li>
                <a href="{% url 'user:utilisateurs'%}"><i class="fas fa-chart-line"></i> utilisateurs</a>
            </li>
            <li>
                <a href="{% url 'rapport:rapport1'%}"><i class="fas fa-chart-line"></i> Rapport</a>
            </li>
        </ul>
        <hr style="margin-top:270px;">
        <ul>
            <li>
                <a href="{% url 'dashbord:index'%}"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            </li>
        </ul>
    </div>

    <div class="content">
        <div class="back-button" style="justify-content: flex-end;" >
            <a href="{% url 'eleve:eleve1'%}"><i class="fas fa-arrow-left"></i> Retour</a>
        </div>

        <div class="form-container">
            <h1>Ajouter un élève</h1>
            <!--Champ Nom-->
                {{form}}
            <div class="form-group">
                <label for="nom">Nom</label>
                <input type="text" id="nom" name="nom">
            </div>

            <div class="form-group">
                <label for="prenom">Prénom</label>
                <input type="text" id="prenom" name="prenom">
            </div>

            <div class="form-group gender">
                <label>Sexe</label>
                <div>
                    <input type="radio" id="homme" name="sexe" value="homme">
                    <label for="homme">Homme</label>
                </div>
                <div>
                    <input type="radio" id="femme" name="sexe" value="femme">
                    <label for="femme">Femme</label>
                </div>
            </div>

            <div class="form-group">
                <label for="matricule">Matricule</label>
                <input type="text" id="matricule" name="matricule">
            </div>

            <div class="form-group">
                <label for="dateNaissance">Date de naissance</label>
                <input type="date" id="dateNaissance" name="dateNaissance">
            </div>

            <div class="form-group">
                <label for="classe">Sélectionner une classe</label>
                <select id="classe" name="classe">
                    <option value="6eme">6ème</option>
                    <option value="5eme">5ème</option>
                    <option value="4eme">4ème</option>
                    <option value="3eme">3ème</option>
                    <option value="2nde">2nde</option>
                    <option value="1ere">1ère</option>
                    <option value="terminale">Terminale</option>
                </select>
            </div>

            <div class="form-group">
                <label for="telephone">Téléphone</label>
                <input type="text" id="telephone" name="telephone">
            </div>

            <div class="form-group">
                <label for="ville">Ville</label>
                <input type="text" id="ville" name="ville">
            </div>

            <div class="form-actions">
                <button class="btn-cancel" onclick="confirmCancel()">Annuler</button>
                <button class="btn-save">Enregistrer</button>
            </div>
        </div>
    </div>
</body>
</html>

eleve/templates/eleve/eleve1.html
 {% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
   
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon Etab - Tableau de bord</title>
    <link rel="stylesheet" href="{% static 'eleve/CSS/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar">
        <h2>Mon Etab</h2>
        <hr>
        <ul>
            <li >
                <a href="{% url 'dashbord:dashboad'%}"><i class="fas fa-tachometer-alt"></i> Tableau de bord</a>
            </li>
            <li class="active">
                <a href="{% url 'eleve:eleve1'%}"><i class="fas fa-user-graduate"></i> Élèves</a>
            </li>
            <li>
                <a href="{% url 'teacher:professeurs'%}"><i class="fas fa-chalkboard-teacher"></i> Professeurs</a>
            </li>
            <li>
                <a href="{% url 'user:utilisateurs'%}"><i class="fas fa-chart-line"></i> utilisateurs</a>
            </li>
            <li>
                <a href="{% url 'rapport:rapport1'%}"><i class="fas fa-chart-line"></i> Rapport</a>
            </li>
        </ul>
        <hr style="margin-top:270px;">
        <ul>
            <li>
                <a href="{% url 'dashbord:index'%}"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            </li>
        </ul>
    </div>
    <div class="content1">
        <div class="back-button">
            <h1 style="color:black;">Liste des élèves</h1>
            <a href="{% url 'eleve:ajout_eleve'%}"><i class="fas fa-arrow-left"></i>Nouveau élève</a>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Genre</th>
                    <th>Classe</th>
                    <th>Matricule</th>
                    <th>Age</th>
                    <th>Téléphone</th>
                    <th>Ville</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>NDOFI</td>
                    <td>George</td>
                    <td>Homme</td>
                    <td>Te</td>
                    <td>030708000</td>
                    <td>25</td>
                    <td>0784545498</td>
                    <td>Abidjan</td>
                    <td>
                        <a href="{% url 'eleve:modifier_eleve'%}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                        <button style="background-color: rgb(212, 21, 21);">Supprimer</button>
                    </td>
                </tr>
                <tr>
                    <td>NONE</td>
                    <td>Suli</td>
                    <td>Femme</td>
                    <td>2nd</td>
                    <td>030708000</td>
                    <td>22</td>
                    <td>0224545498</td>
                    <td>Abidjan</td>
                    <td>
                        <a href="{% url 'eleve:modifier_eleve'%}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                        <button style="background-color: rgb(212, 21, 21);">Supprimer</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <script src="{% static 'eleve/JS/scripte.js' %}"></script>
    <script>
        function confirmerSuppression(event) {
            event.preventDefault(); // Empêche l'action par défaut du bouton
        
            // Afficher une boîte de confirmation
            const confirmation = confirm("Attention, vous êtes sur le point de supprimer cet élève ! Voulez-vous vraiment continuer ?");
        
            // Si l'utilisateur clique sur "OK", la suppression est confirmée
            if (confirmation) {
                // Ajoutez ici le code pour supprimer l'élève
                alert('L\'élève a été supprimé.');
            } else {
                // Si l'utilisateur clique sur "Annuler", la suppression est annulée
                alert('Suppression annulée.');
            }
        }
        
        // Attacher l'événement de clic aux boutons "Supprimer"
        document.querySelectorAll('button[style*="rgb(212, 21, 21)"]').forEach(button => {
            button.addEventListener('click', confirmerSuppression);
        });
        </script>
</body>
</html>

eleve/templates/eleve/modifier_eleve.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier un élève</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'eleve/CSS/styles.css' %}">
</head>
<body>
    <div class="sidebar">
        <h2>Mon Etab</h2>
        <hr>
        <ul>
            <li >
                <a href="{% url 'dashbord:dashboad'%}"><i class="fas fa-tachometer-alt"></i> Tableau de bord</a>
            </li>
            <li class="active">
                <a href="{% url 'eleve:eleve1'%}"><i class="fas fa-user-graduate"></i> Élèves</a>
            </li>
            <li>
                <a href="{% url 'teacher:professeurs'%}"><i class="fas fa-chalkboard-teacher"></i> Professeurs</a>
            </li>
            <li>
                <a href="{% url 'user:utilisateurs'%}"><i class="fas fa-chart-line"></i> utilisateurs</a>
            </li>
            <li>
                <a href="{% url 'rapport:rapport1'%}"><i class="fas fa-chart-line"></i> Rapport</a>
            </li>
        </ul>
        <hr style="margin-top:270px;">
        <ul>
            <li>
                <a href="{% url 'dashbord:index'%}"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            </li>
        </ul>
    </div>

    <div class="content">
        <div class="back-button" style="justify-content: flex-end;" >
            <a href="{% url 'eleve:eleve1'%}"><i class="fas fa-arrow-left"></i> Retour</a>
        </div>

        <div class="form-container">
            <h1>Modifier un élève</h1>
            <!--Champ form-->
                {{form}}
            <div class="form-group">
                <label for="nom">Nom</label>
                <input type="text" id="nom" name="nom">
            </div>

            <div class="form-group">
                <label for="prenom">Prénom</label>
                <input type="text" id="prenom" name="prenom">
            </div>

            <div class="form-group gender">
                <label>Sexe</label>
                <div>
                    <input type="radio" id="homme" name="sexe" value="homme">
                    <label for="homme">Homme</label>
                </div>
                <div>
                    <input type="radio" id="femme" name="sexe" value="femme">
                    <label for="femme">Femme</label>
                </div>
            </div>

            <div class="form-group">
                <label for="matricule">Matricule</label>
                <input type="text" id="matricule" name="matricule">
            </div>

            <div class="form-group">
                <label for="dateNaissance">Date de naissance</label>
                <input type="date" id="dateNaissance" name="dateNaissance">
            </div>

            <div class="form-group">
                <label for="classe">Sélectionner une classe</label>
                <select id="classe" name="classe">
                    <option value="6eme">6ème</option>
                    <option value="5eme">5ème</option>
                    <option value="4eme">4ème</option>
                    <option value="3eme">3ème</option>
                    <option value="2nde">2nde</option>
                    <option value="1ere">1ère</option>
                    <option value="terminale">Terminale</option>
                </select>
            </div>

            <div class="form-group">
                <label for="telephone">Téléphone</label>
                <input type="text" id="telephone" name="telephone">
            </div>

            <div class="form-group">
                <label for="ville">Ville</label>
                <input type="text" id="ville" name="ville">
            </div>

            <div class="form-actions">
                <button class="btn-cancel" onclick="confirmCancel()">Annuler</button>
                <button class="btn-save">Enregistrer</button>
            </div>
        </div>
    </div>
</body>
</html>

teacher/templates/teacher/professeurs.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon Etab - Tableau de bord</title>
    <link rel="stylesheet" href="{% static 'teacher/CSS/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar">
        <h2>Mon Etab</h2>
        <hr>
        <ul>
            <li >
                <a href="{% url 'dashbord:dashboad'%}"><i class="fas fa-tachometer-alt"></i> Tableau de bord</a>
            </li>
            <li>
                <a href="{% url 'eleve:eleve1'%}"><i class="fas fa-user-graduate"></i> Élèves</a>
            </li>
            <li class="active">
                <a href="{% url 'teacher:professeurs'%}"><i class="fas fa-chalkboard-teacher"></i> Professeurs</a>
            </li>
            <li>
                <a href="{% url 'user:utilisateurs'%}"><i class="fas fa-chart-line"></i> utilisateurs</a>
            </li>
            <li>
                <a href="{% url 'rapport:rapport1'%}"><i class="fas fa-chart-line"></i> Rapport</a>
            </li>
        </ul>
        <hr style="margin-top:270px;">
        <ul>
            <li>
                <a href="{% url 'dashbord:index'%}"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            </li>
        </ul>
    </div>
    <div class="content1">
        <div class="back-button">
            <h1 style="color:black;">Liste des professeurs</h1>
            <a href="{% url 'teacher:ajout_prof'%}"><i class="fas fa-arrow-left"></i>Nouveau professeurs</a>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Genre</th>
                    <th>Matière</th>
                    <th>Matricule</th>
                    <th>Age</th>
                    <th>Téléphone</th>
                    <th>Ville</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>NDOFI</td>
                    <td>George</td>
                    <td>Homme</td>
                    <td>Maths</td>
                    <td>030708000</td>
                    <td>25</td>
                    <td>0784545498</td>
                    <td>Abidjan</td>
                    <td>
                        <a href="{% url 'teacher:modifier_prof'%}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                        <button style="background-color: rgb(212, 21, 21);">Supprimer</button>
                    </td>
                </tr>
                <tr>
                    <td>NONE</td>
                    <td>Suli</td>
                    <td>Femme</td>
                    <td>Français</td>
                    <td>030708000</td>
                    <td>22</td>
                    <td>0224545498</td>
                    <td>Abidjan</td>
                    <td>
                        <a href="{% url 'teacher:modifier_prof'%}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                        <button style="background-color: rgb(212, 21, 21);">Supprimer</button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <script src="{% static 'teacher/JS/scripte.js' %}"></script>
    <script>
        function confirmerSuppression(event) {
            event.preventDefault(); // Empêche l'action par défaut du bouton
        
            // Afficher une boîte de confirmation
            const confirmation = confirm("Attention, vous êtes sur le point de supprimer cet professeur ! Voulez-vous vraiment continuer ?");
        
            // Si l'utilisateur clique sur "OK", la suppression est confirmée
            if (confirmation) {
                // Ajoutez ici le code pour supprimer l'élève
                alert('Le professeur a été supprimé.');
            } else {
                // Si l'utilisateur clique sur "Annuler", la suppression est annulée
                alert('Suppression annulée.');
            }
        }
        
        // Attacher l'événement de clic aux boutons "Supprimer"
        document.querySelectorAll('button[style*="rgb(212, 21, 21)"]').forEach(button => {
            button.addEventListener('click', confirmerSuppression);
        });
        </script>
</body>
</html>

user/templates/user/utilisateurs.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon Etab - Tableau de bord</title>
    <link rel="stylesheet" href="{% static 'user/CSS/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="sidebar">
        <h2>Mon Etab</h2>
        <hr>
        <ul>
            <li >
                <a href="{% url 'dashbord:dashboad'%}"><i class="fas fa-tachometer-alt"></i> Tableau de bord</a>
            </li>
            <li >
                <a href="{% url 'eleve:eleve1'%}"><i class="fas fa-user-graduate"></i> Élèves</a>
            </li>
            <li>
                <a href="{% url 'teacher:professeurs'%}"><i class="fas fa-chalkboard-teacher"></i> Professeurs</a>
            </li>
            <li class="active">
                <a href="{% url 'user:utilisateurs'%}"><i class="fas fa-chart-line"></i> utilisateurs</a>
            </li>
            <li>
                <a href="{% url 'rapport:rapport1'%}"><i class="fas fa-chart-line"></i> Rapport</a>
            </li>
        </ul>
        <hr style="margin-top:270px;">
        <ul>
            <li>
                <a href="{% url 'dashbord:index'%}"><i class="fas fa-sign-out-alt"></i> Déconnexion</a>
            </li>
        </ul>
    </div>
    <div class="content1">
        <div class="back-button">
            <h1 style="color:black;">Liste des Utilisateurs</h1>
            <a href="{% url 'user:ajout_utilisateur'%}"><i class="fas fa-arrow-left"></i>Nouveau utilisateur</a>
        </div>
        <table>
            <thead>
                <tr>
                    <th>Pseudo</th>
                    <th>Date de création</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>admin</td>
                    <td>16/08/2024</td>
                    
                    <td>
                        <a href="{% url 'user:modifier_utilisateur'%}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                        
                    </td>
                </tr>
                <tr>
                    <td>user2</td>
                    <td>13/08/2024</td>
                    <td>
                        <a href="{% url 'user:modifier_utilisateur'%}" style="background-color: rgba(255, 217, 0, 0.897);">Modifier</a>
                        
                        
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <script src="{% static 'user/JS/scripte.js'%}"></script>
    <script>
        function confirmerSuppression(event) {
            event.preventDefault(); // Empêche l'action par défaut du bouton
        
            // Afficher une boîte de confirmation
            const confirmation = confirm("Attention, vous êtes sur le point de supprimer cet élève ! Voulez-vous vraiment continuer ?");
        
            // Si l'utilisateur clique sur "OK", la suppression est confirmée
            if (confirmation) {
                // Ajoutez ici le code pour supprimer l'élève
                alert('L\'utilisateur a été supprimé.');
            } else {
                // Si l'utilisateur clique sur "Annuler", la suppression est annulée
                alert('Suppression annulée.');
            }
        }
        
        // Attacher l'événement de clic aux boutons "Supprimer"
        document.querySelectorAll('button[style*="rgb(212, 21, 21)"]').forEach(button => {
            button.addEventListener('click', confirmerSuppression);
        });
        </script>
</body>
</html>